### ISSUE TITLE
SHOW LATENCY计算问题

### ISSUE THREAD

**Issue by zhangyang3** [variflight/feeyo-redisproxy#122]
我的理解：SHOW LATENCY指令中的time和latency 应该是某个毫秒内的平均纳秒延时。
但是PhysicalNode的350行：total = v.latency;  此处不应该是total+=v.latency么？

**Comment by zhuam** [comment]
是个bug,  但不影响实际的采样和计算及熔断，但 getSparseSamples 影响了后端的查询指令，造成这个数据的输出错误
