### ISSUE TITLE
使用问题：因为现在只在windows上启用了一个单节点。但是始终不能运行set和get命令。如下图，请您告知一下是什么问题

### ISSUE THREAD

**Issue by huafengwu15** [variflight/feeyo-redisproxy#160]
PS C:\WINDOWS\system32> redis-cli -h localhost -p 6379 -a pwd05
localhost:6379> slect 1
OK
localhost:6379> set wu 1222
(error) NOAUTH Authentication required.
(5.16s)
localhost:6379>
在上面已经设置了密码了。没有用。即使后面在通过auth pwd05设置密码，也没有作用。
请您解答一下，谢谢您了

**Comment by zhuam** [comment]
参见 user.xml ，Eg: <user password="pwd04" poolId="1" prefix="pre1_" selectDb="0" />
, 你需要进行认证， auth pwd04 ，之后在进行 set / get  ....

**Comment by zhuam** [comment]
参见 user.xml ，Eg: <user password="pwd04"
, 你需要进行认证， auth pwd04 ，之后在进行 set / get ....
