### ISSUE TITLE
通过虚拟内存，解决pipeline数据堆积问题咨询

### ISSUE THREAD

**Issue by beifeng15** [variflight/feeyo-redisproxy#162]
我想请问一下您以下问题：
     1.现在Redis已经舍弃了虚拟内存，那么您在项目中提到的使用虚拟内存解决数据堆积问题，是否可行？
     2.
![image](https://user-images.githubusercontent.com/43507256/101027330-dc376200-35b2-11eb-93b1-536127b8389e.png)
  我在进行上图测试pipeline的时候，一直出错，然后查看了redis库，100条数据，报错了，并且只有29条插入成功了。

    3.我想知道使用虚拟内存解决pipeline的大概原理。主要是程序中的类调用关系和作用，因为我看不懂这一部分的程序，您能大致说一下就行了。（我真的想弄明白）
   谢谢您了！

**Comment by zhuam** [comment]
所谓虚拟内存解决堆积问题，是因为我们这部分使用了rocketmq 的方式，将应答数据mmap 的方式写入到文件， 另外 pipeline 超过29条报错？ trace 能提供吗
